name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20.5' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install build tools
        run: make install-build-tools
      - name: Install dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: Build
        run: make build
      - name: Test with Go
        run: make test
